kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: unified-logging
    service: unified-logging-coord
  name: unified-logging-coord
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: management
      component: unified-logging
      service: unified-logging-coord
  template:
    metadata:
      labels:
        cluster: management
        component: unified-logging
        service: unified-logging-coord
    spec:
      containers:
      - name: unified-logging-coord
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/unified-logging-coord:__NPH_VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        env:
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: management-config
                key: environment
        args:
        - "run"
        - "--debug"
        - "--caCertPath=/nalej/tls-ca-certificate/tls.crt"
        - "--clientCertPath=/nalej/tls-client-certificate/tls.crt"
        - "--skipServerCertValidation=false"
        ports:
        - name: api-port
          containerPort: 8323
        volumeMounts:
        - name: tls-ca-certificate-volume
          readOnly: true
          mountPath: /nalej/tls-ca-certificate
        - name: tls-client-certificate-volume
          readOnly: true
          mountPath: /nalej/tls-client-certificate
      imagePullSecrets:
      - name: nalej-registry
      volumes:
        - name: tls-ca-certificate-volume
          secret:
            secretName: tls-ca-certificate
        - name: tls-client-certificate-volume
          secret:
            secretName: tls-client-certificate