kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: unified-logging
    service: unified-logging-coord
  name: unified-logging-slave
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: management
      component: unified-logging
      service: unified-logging-coord
  template:
    metadata:
      labels:
        cluster: management
        component: unified-logging
        service: unified-logging-coord
    spec:
      containers:
      - name: unified-logging-coord
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/unified-logging-coord:__NPH_VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        args:
        - "run"
        - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
        ports:
        - name: api-port
          containerPort: 8323
      imagePullSecrets:
      - name: nalej-registry
