kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elastic
  namespace: __NPH_NAMESPACE
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  # storageClassName: nalej-storage
