apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: __NPH_NAMESPACE
  labels:
    cluster: application
    component: unified-logging
    service: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: application
      component: unified-logging
      service: elastic
  template:
    metadata:
      labels:
        cluster: application
        component: unified-logging
        service: elastic
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: processors
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          readOnly: true
      volumes:
        - name: "storage"
          persistentVolumeClaim:
            claimName: elastic
        - name: config
          configMap:
            defaultMode: 0644
            name: elastic
