apiVersion: v1
kind: Service
metadata:
  name: elastic
  namespace: __NPH_NAMESPACE
  labels:
    cluster: application
    component: unified-logging
    service: elastic
spec:
  selector:
    cluster: application
    component: unified-logging
    service: elastic
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
    protocol: TCP
