apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs
  namespace: __NPH_NAMESPACE
  labels:
    cluster: application
    component: unified-logging
    service: filebeat
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
