apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: __NPH_NAMESPACE
  labels:
    cluster: application
    component: unified-logging
    service: filebeat
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        enabled: true
        # Mounted `filebeat-inputs` configmap:
        path: ${path.config}/inputs.d/*.yml
      modules:
        enabled: true
        path: ${path.config}/modules.d/*.yml
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
