kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: application
    component: unified-logging
    service: unified-logging-slave
  name: unified-logging-slave
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: application
      component: unified-logging
      service: unified-logging-slave
  template:
    metadata:
      labels:
        cluster: application
        component: unified-logging
        service: unified-logging-slave
    spec:
      containers:
      - name: unified-logging-slave
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/unified-logging-slave:__NPH_VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        args:
        - "run"
        - "--elasticAddress=elastic.__NPH_NAMESPACE:9200"
        ports:
        - name: api-port
          containerPort: 8322
      imagePullSecrets:
      - name: nalej-registry
